export interface Match {
  stage: string;
  group: string;
  date: string;
  time: string;
  homeTeam: string;
  awayTeam: string;
}

export const SCHEDULE_DATA: Match[] = [
  { stage: "Group Stage", group: "A", date: "Jun 11", time: "3:00 PM", homeTeam: "Mexico", awayTeam: "South Africa" },
  { stage: "Group Stage", group: "A", date: "Jun 11", time: "10:00 PM", homeTeam: "South Korea", awayTeam: "Czechia" },
  { stage: "Group Stage", group: "B", date: "Jun 12", time: "3:00 PM", homeTeam: "Canada", awayTeam: "Bosnia and Herzegovina" },
  { stage: "Group Stage", group: "D", date: "Jun 12", time: "9:00 PM", homeTeam: "USA", awayTeam: "Paraguay" },
  { stage: "Group Stage", group: "B", date: "Jun 13", time: "3:00 PM", homeTeam: "Qatar", awayTeam: "Switzerland" },
  { stage: "Group Stage", group: "C", date: "Jun 13", time: "6:00 PM", homeTeam: "Brazil", awayTeam: "Morocco" },
  { stage: "Group Stage", group: "C", date: "Jun 13", time: "9:00 PM", homeTeam: "Haiti", awayTeam: "Scotland" },
  { stage: "Group Stage", group: "D", date: "Jun 14", time: "12:00 AM", homeTeam: "Australia", awayTeam: "Türkiye" },
  { stage: "Group Stage", group: "E", date: "Jun 14", time: "1:00 PM", homeTeam: "Germany", awayTeam: "Curaçao" },
  { stage: "Group Stage", group: "F", date: "Jun 14", time: "4:00 PM", homeTeam: "Netherlands", awayTeam: "Japan" },
  { stage: "Group Stage", group: "E", date: "Jun 14", time: "7:00 PM", homeTeam: "Ivory Coast", awayTeam: "Ecuador" },
  { stage: "Group Stage", group: "F", date: "Jun 14", time: "10:00 PM", homeTeam: "Sweden", awayTeam: "Tunisia" },
  { stage: "Group Stage", group: "H", date: "Jun 15", time: "12:00 PM", homeTeam: "Spain", awayTeam: "Cape Verde" },
  { stage: "Group Stage", group: "G", date: "Jun 15", time: "3:00 PM", homeTeam: "Belgium", awayTeam: "Egypt" },
  { stage: "Group Stage", group: "H", date: "Jun 15", time: "6:00 PM", homeTeam: "Saudi Arabia", awayTeam: "Uruguay" },
  { stage: "Group Stage", group: "G", date: "Jun 15", time: "9:00 PM", homeTeam: "Iran", awayTeam: "New Zealand" },
  { stage: "Group Stage", group: "I", date: "Jun 16", time: "3:00 PM", homeTeam: "France", awayTeam: "Senegal" },
  { stage: "Group Stage", group: "I", date: "Jun 16", time: "6:00 PM", homeTeam: "Iraq", awayTeam: "Norway" },
  { stage: "Group Stage", group: "J", date: "Jun 16", time: "9:00 PM", homeTeam: "Argentina", awayTeam: "Algeria" },
  { stage: "Group Stage", group: "J", date: "Jun 17", time: "12:00 AM", homeTeam: "Austria", awayTeam: "Jordan" },
  { stage: "Group Stage", group: "K", date: "Jun 17", time: "1:00 PM", homeTeam: "Portugal", awayTeam: "DR Congo" },
  { stage: "Group Stage", group: "L", date: "Jun 17", time: "4:00 PM", homeTeam: "England", awayTeam: "Croatia" },
  { stage: "Group Stage", group: "L", date: "Jun 17", time: "7:00 PM", homeTeam: "Ghana", awayTeam: "Panama" },
  { stage: "Group Stage", group: "K", date: "Jun 17", time: "10:00 PM", homeTeam: "Uzbekistan", awayTeam: "Colombia" },
  { stage: "Group Stage", group: "A", date: "Jun 18", time: "12:00 PM", homeTeam: "Czechia", awayTeam: "South Africa" },
  { stage: "Group Stage", group: "B", date: "Jun 18", time: "3:00 PM", homeTeam: "Switzerland", awayTeam: "Bosnia and Herzegovina" },
  { stage: "Group Stage", group: "B", date: "Jun 18", time: "6:00 PM", homeTeam: "Canada", awayTeam: "Qatar" },
  { stage: "Group Stage", group: "A", date: "Jun 18", time: "9:00 PM", homeTeam: "Mexico", awayTeam: "South Korea" },
  { stage: "Group Stage", group: "D", date: "Jun 19", time: "3:00 PM", homeTeam: "USA", awayTeam: "Australia" },
  { stage: "Group Stage", group: "C", date: "Jun 19", time: "6:00 PM", homeTeam: "Scotland", awayTeam: "Morocco" },
  { stage: "Group Stage", group: "C", date: "Jun 19", time: "8:30 PM", homeTeam: "Brazil", awayTeam: "Haiti" },
  { stage: "Group Stage", group: "D", date: "Jun 19", time: "11:00 PM", homeTeam: "Türkiye", awayTeam: "Paraguay" },
  { stage: "Group Stage", group: "F", date: "Jun 20", time: "1:00 PM", homeTeam: "Netherlands", awayTeam: "Sweden" },
  { stage: "Group Stage", group: "E", date: "Jun 20", time: "4:00 PM", homeTeam: "Germany", awayTeam: "Ivory Coast" },
  { stage: "Group Stage", group: "E", date: "Jun 20", time: "8:00 PM", homeTeam: "Ecuador", awayTeam: "Curaçao" },
  { stage: "Group Stage", group: "F", date: "Jun 21", time: "12:00 AM", homeTeam: "Tunisia", awayTeam: "Japan" },
  { stage: "Group Stage", group: "H", date: "Jun 21", time: "12:00 PM", homeTeam: "Spain", awayTeam: "Saudi Arabia" },
  { stage: "Group Stage", group: "G", date: "Jun 21", time: "3:00 PM", homeTeam: "Belgium", awayTeam: "Iran" },
  { stage: "Group Stage", group: "H", date: "Jun 21", time: "6:00 PM", homeTeam: "Uruguay", awayTeam: "Cape Verde" },
  { stage: "Group Stage", group: "G", date: "Jun 21", time: "9:00 PM", homeTeam: "New Zealand", awayTeam: "Egypt" },
  { stage: "Group Stage", group: "J", date: "Jun 22", time: "1:00 PM", homeTeam: "Argentina", awayTeam: "Austria" },
  { stage: "Group Stage", group: "I", date: "Jun 22", time: "5:00 PM", homeTeam: "France", awayTeam: "Iraq" },
  { stage: "Group Stage", group: "I", date: "Jun 22", time: "8:00 PM", homeTeam: "Norway", awayTeam: "Senegal" },
  { stage: "Group Stage", group: "J", date: "Jun 22", time: "11:00 PM", homeTeam: "Jordan", awayTeam: "Algeria" },
  { stage: "Group Stage", group: "K", date: "Jun 23", time: "1:00 PM", homeTeam: "Portugal", awayTeam: "Uzbekistan" },
  { stage: "Group Stage", group: "L", date: "Jun 23", time: "4:00 PM", homeTeam: "England", awayTeam: "Ghana" },
  { stage: "Group Stage", group: "L", date: "Jun 23", time: "7:00 PM", homeTeam: "Panama", awayTeam: "Croatia" },
  { stage: "Group Stage", group: "K", date: "Jun 23", time: "10:00 PM", homeTeam: "Colombia", awayTeam: "DR Congo" },
  { stage: "Group Stage", group: "B", date: "Jun 24", time: "3:00 PM", homeTeam: "Switzerland", awayTeam: "Canada" },
  { stage: "Group Stage", group: "B", date: "Jun 24", time: "3:00 PM", homeTeam: "Bosnia and Herzegovina", awayTeam: "Qatar" },
  { stage: "Group Stage", group: "C", date: "Jun 24", time: "6:00 PM", homeTeam: "Morocco", awayTeam: "Haiti" },
  { stage: "Group Stage", group: "C", date: "Jun 24", time: "6:00 PM", homeTeam: "Scotland", awayTeam: "Brazil" },
  { stage: "Group Stage", group: "A", date: "Jun 24", time: "9:00 PM", homeTeam: "South Africa", awayTeam: "South Korea" },
  { stage: "Group Stage", group: "A", date: "Jun 24", time: "9:00 PM", homeTeam: "Czechia", awayTeam: "Mexico" },
  { stage: "Group Stage", group: "E", date: "Jun 25", time: "4:00 PM", homeTeam: "Curaçao", awayTeam: "Ivory Coast" },
  { stage: "Group Stage", group: "E", date: "Jun 25", time: "4:00 PM", homeTeam: "Ecuador", awayTeam: "Germany" },
  { stage: "Group Stage", group: "F", date: "Jun 25", time: "7:00 PM", homeTeam: "Tunisia", awayTeam: "Netherlands" },
  { stage: "Group Stage", group: "F", date: "Jun 25", time: "7:00 PM", homeTeam: "Japan", awayTeam: "Sweden" },
  { stage: "Group Stage", group: "D", date: "Jun 25", time: "10:00 PM", homeTeam: "Türkiye", awayTeam: "USA" },
  { stage: "Group Stage", group: "D", date: "Jun 25", time: "10:00 PM", homeTeam: "Paraguay", awayTeam: "Australia" },
  { stage: "Group Stage", group: "I", date: "Jun 26", time: "3:00 PM", homeTeam: "Norway", awayTeam: "France" },
  { stage: "Group Stage", group: "I", date: "Jun 26", time: "3:00 PM", homeTeam: "Senegal", awayTeam: "Iraq" },
  { stage: "Group Stage", group: "H", date: "Jun 26", time: "8:00 PM", homeTeam: "Cape Verde", awayTeam: "Saudi Arabia" },
  { stage: "Group Stage", group: "H", date: "Jun 26", time: "8:00 PM", homeTeam: "Uruguay", awayTeam: "Spain" },
  { stage: "Group Stage", group: "G", date: "Jun 26", time: "11:00 PM", homeTeam: "New Zealand", awayTeam: "Belgium" },
  { stage: "Group Stage", group: "G", date: "Jun 26", time: "11:00 PM", homeTeam: "Egypt", awayTeam: "Iran" },
  { stage: "Group Stage", group: "L", date: "Jun 27", time: "5:00 PM", homeTeam: "Panama", awayTeam: "England" },
  { stage: "Group Stage", group: "L", date: "Jun 27", time: "5:00 PM", homeTeam: "Croatia", awayTeam: "Ghana" },
  { stage: "Group Stage", group: "K", date: "Jun 27", time: "7:30 PM", homeTeam: "Colombia", awayTeam: "Portugal" },
  { stage: "Group Stage", group: "K", date: "Jun 27", time: "7:30 PM", homeTeam: "DR Congo", awayTeam: "Uzbekistan" },
  { stage: "Group Stage", group: "J", date: "Jun 27", time: "10:00 PM", homeTeam: "Algeria", awayTeam: "Austria" },
  { stage: "Group Stage", group: "J", date: "Jun 27", time: "10:00 PM", homeTeam: "Jordan", awayTeam: "Argentina" },
  { stage: "Round of 32", group: "—", date: "Jun 28", time: "3:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 32", group: "—", date: "Jun 29", time: "1:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 32", group: "—", date: "Jun 29", time: "4:30 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 32", group: "—", date: "Jun 29", time: "9:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 32", group: "—", date: "Jun 30", time: "1:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 32", group: "—", date: "Jun 30", time: "5:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 32", group: "—", date: "Jun 30", time: "9:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 32", group: "—", date: "Jul 1", time: "12:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 32", group: "—", date: "Jul 1", time: "4:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 32", group: "—", date: "Jul 1", time: "8:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 32", group: "—", date: "Jul 2", time: "3:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 32", group: "—", date: "Jul 2", time: "7:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 32", group: "—", date: "Jul 2", time: "11:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 32", group: "—", date: "Jul 3", time: "2:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 32", group: "—", date: "Jul 3", time: "6:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 32", group: "—", date: "Jul 3", time: "9:30 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 16", group: "—", date: "Jul 4", time: "1:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 16", group: "—", date: "Jul 4", time: "5:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 16", group: "—", date: "Jul 5", time: "4:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 16", group: "—", date: "Jul 5", time: "8:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 16", group: "—", date: "Jul 6", time: "3:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 16", group: "—", date: "Jul 6", time: "8:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 16", group: "—", date: "Jul 7", time: "12:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Round of 16", group: "—", date: "Jul 7", time: "4:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Quarter-finals", group: "—", date: "Jul 9", time: "4:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Quarter-finals", group: "—", date: "Jul 10", time: "3:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Quarter-finals", group: "—", date: "Jul 11", time: "5:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Quarter-finals", group: "—", date: "Jul 11", time: "9:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Semi-finals", group: "—", date: "Jul 14", time: "3:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Semi-finals", group: "—", date: "Jul 15", time: "3:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Third place play-off", group: "—", date: "Jul 18", time: "5:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
  { stage: "Final", group: "—", date: "Jul 19", time: "3:00 PM", homeTeam: "TBD", awayTeam: "TBD" },
];
